<a href="https://colab.research.google.com/github/nitinware/GoogleCloabNotebooks/blob/master/tensor_serving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

In [4]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [5]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [10]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [12]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [14]:
model.fit(X_train, y_train, epochs=50)

Epoch 1/50
39/39 [==============================] - 1s 2ms/step - loss: 0.8010 - accuracy: 0.4617
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.6207 - accuracy: 0.5957
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4843 - accuracy: 0.8422
Epoch 4/50
39/39 [==============================] - 0s 1ms/step - loss: 0.3754 - accuracy: 0.9603
Epoch 5/50
39/39 [==============================] - 0s 1ms/step - loss: 0.2980 - accuracy: 0.9580
Epoch 6/50
39/39 [==============================] - 0s 1ms/step - loss: 0.2413 - accuracy: 0.9621
Epoch 7/50
39/39 [==============================] - 0s 1ms/step - loss: 0.1896 - accuracy: 0.9628
Epoch 8/50
39/39 [==============================] - 0s 1ms/step - loss: 0.1780 - accuracy: 0.9529
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1639 - accuracy: 0.9503
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1421 - accuracy: 0.9556
Epoch 11/50
39/39 [

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 22        
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [16]:
loss, accuracy = model.evaluate(X_test, y_test)

10/10 [==============================] - 0s 2ms/step - loss: 0.1069 - accuracy: 0.9550


In [17]:
loss

0.10694900155067444

In [18]:
accuracy

0.9549839496612549

In [19]:
prediction1 = model.predict(sc.transform(np.array([[42, 50000]])))[:1]

In [20]:
prediction1

array([[0.35106704, 0.64893293]], dtype=float32)

In [24]:
prediction2 = model.predict(sc.transform(np.array([[20, 40000]])))

In [25]:
prediction2

array([[0.9952271 , 0.00477293]], dtype=float32)

In [26]:
model.save('customer_behavior_model/1')

INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [27]:
!ls

customer_behavior_model  sample_data


In [28]:
!ls customer_behavior_model/1

assets	saved_model.pb	variables


In [30]:
from tensorflow.keras.models import load_model

In [31]:
cust_model = load_model('customer_behavior_model/1/')

In [34]:
prediction4 = cust_model.predict(sc.transform(np.array([[42, 50000]])))[:,1]

In [35]:
prediction4

array([0.64893293], dtype=float32)

In [36]:
!zip -r customermodel.zip customer_behavior_model

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 54%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/assets/ (stored 0%)


In [37]:
from google.colab import files

In [38]:
!ls

customer_behavior_model  customermodel.zip  sample_data


In [39]:
files.download('customermodel.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>